const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNIN';
const GET_FAIL="GET_FAIL";
const GET_SUCCESS="GET_SUCCESS";
const GET_REQUEST="GET_REQUEST";

export {USER_SIGNIN,USER_SIGNOUT,GET_FAIL,GET_SUCCESS,GET_REQUEST}