const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNIN';
const GET_FAIL="GET_FAIL";
const GET_SUCCESS="GET_SUCCESS";
const GET_REQUEST="GET_REQUEST";
const ADD_TO_MY_LIST="ADD_TO_MY_LIST";
const REMOVE_FROM_MY_LIST="REMOVE_FROM_MY_LIST";
const GET_MY_LIST="GET_MY_LIST";





export {USER_SIGNIN,USER_SIGNOUT,GET_FAIL,GET_SUCCESS,GET_REQUEST,ADD_TO_MY_LIST,REMOVE_FROM_MY_LIST, GET_MY_LIST}